// Generated by CoffeeScript 1.12.6
(function() {
  var Generator, engine;

  Generator = (function() {
    function Generator() {
      this.last_names = ['the Chef', 'Digital', 'Wise', 'Knight', 'Wrecka', 'the Genius', 'the Zoo Keeper', 'the Monk', 'the Scientist', 'the Disciple', 'the Darkman', 'Pellegrino', 'the Ill Figure', 'Rocks The World', 'the Baptist'];
      this.first_names = ['Inspectah', 'Masta', 'Poppa', 'Five Foot', 'Ghostface', 'Old Dirty'];
      this.transforms = [
        (function(s) {
          return s.toUpperCase()[0];
        }), (function(s) {
          return s.toUpperCase().split('').join('.') + '.';
        }), (function(s) {
          return s.replace(/s|S/g, '$$$$');
        }), (function(s) {
          return s;
        })
      ];
    }

    Generator.prototype.get_name = function(submitted_name) {
      var name, structures;
      structures = [this.first_names.random() + ' {}', this.first_names.random() + ' {} ' + this.last_names.random(), '{} ' + this.last_names.random()];
      name = this.transforms.random()(submitted_name);
      return structures.random().replace('{}', name);
    };

    return Generator;

  })();

  Array.prototype.random = function() {
    return this[Math.floor(Math.random() * this.length)];
  };

  engine = new Generator;

  $('.response, .error').hide();

  $('#enter').click(function() {
    var input, name;
    $('.response, .error').hide();
    input = $('#user-input').val();
    if (input.length > 0) {
      name = engine.get_name(input);
      $('.response').text(name);
      $('.response').show();
    } else {
      $('.error').show();
    }
    return true;
  });

}).call(this);
